# Generated by Django 5.1.3 on 2024-11-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('num_teams', models.IntegerField(default=0)),
                ('num_games', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('place_in_standings', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('star_mult', models.IntegerField()),
                ('roster_lineup', models.JSONField(blank=True, default=list)),
                ('team_schedule', models.JSONField(blank=True, default=list)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('position', models.TextField()),
                ('star', models.BooleanField(default=False)),
                ('dob', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_scored_team1', models.IntegerField(default=0)),
                ('points_scored_team2', models.IntegerField(default=0)),
                ('winner', models.TextField(blank=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='project.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='project.team')),
            ],
        ),
    ]
