# Generated by Django 5.1.3 on 2024-12-07 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_league_user_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
